---
services:
  mirror:
    container_name: apt-mirror
    hostname: apt-mirror
    image: neofob/apt-mirror:mirror
    build: .
    restart: unless-stopped
    volumes:
      - "${MIRROR}:/var/spool/apt-mirror"
      - "${MIRROR_LIST}:/etc/apt/mirror.list:ro"
      - "${POST_MIRROR}:/var/spool/apt-mirror/var/postmirror.sh:ro"
      - "${CRONTAB_DIR}:/etc/cron.d:ro"
    tmpfs:
      - "/var/run"
      - "/var/log"
    deploy:
      resources:
        limits:
          memory: 512M

  server:
    container_name: apt-mirror-server
    hostname: apt-mirror-server
    image: neofob/apt-mirror:server
    build:
      context: .
      dockerfile: nginx.Dockerfile
    command: [nginx-debug, '-g', 'daemon off;']
    restart: unless-stopped
    volumes:
      - "${MIRROR_DIR}:/mirror:ro"
      - "${NGINX_CONF}:/etc/nginx/conf.d/mirror.conf:ro"
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 256M
